name: JFrog CLI Test

on:
  push:
    branches: [ "main" ]

jobs:
  jfrog-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Verify JFrog connection
        run: jf rt ping
      - name: Docker login to Artifactory
        run: |
          echo ${{ secrets.JF_ACCESS_TOKEN }} | docker login \
            ${{ secrets.JF_URL }} \
            --username unused \
            --password-stdin

      - name: Pull image from Artifactory
        run: |
          docker pull docker-local/nginx:1.23

      - name: Scan image and fail build
        run: |
          jf docker scan docker-local/nginx:1.23 --fail=true
